version: '3'

services:
  postgres:
    container_name: reserva_db
    image: postgres:11.2
    ports:
      - "5432:5432"
    environment:
      - DB_USER="postgres"
      - DB_PASS="postgres"
      - DB_NAME="reserva_dev"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
